import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navbar";

export const metadata = {
  title: "Smart Study Planner",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin']
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
